import {
  DashboardOverview,
  LocationSummary,
  RiskAssessment,
  AlertItem,
  InspectionTask,
  InfrastructureAsset,
  HistoricalLandslide,
  DataSourceHealth
} from '../types';

export const fallbackLocations: LocationSummary[] = [
  {
    id: 1,
    code: 'KL-WAY-01',
    name: 'Meppadi - Chooralmala Catchment',
    district: 'Wayanad',
    state: 'Kerala',
    latitude: 11.5365,
    longitude: 76.1322,
    elevation_m: 880.0,
    population: 14200,
    is_demo: true,
  },
  {
    id: 2,
    code: 'KL-IDK-02',
    name: 'Pettimudi - Munnar Valley',
    district: 'Idukki',
    state: 'Kerala',
    latitude: 10.1528,
    longitude: 77.0142,
    elevation_m: 1540.0,
    population: 8900,
    is_demo: true,
  },
  {
    id: 3,
    code: 'UK-CHA-03',
    name: 'Joshimath - Helang Slope',
    district: 'Chamoli',
    state: 'Uttarakhand',
    latitude: 30.5562,
    longitude: 79.5654,
    elevation_m: 1890.0,
    population: 23500,
    is_demo: true,
  },
  {
    id: 4,
    code: 'HP-SHI-04',
    name: 'Summer Hill - Shiv Bawdi Ridge',
    district: 'Shimla',
    state: 'Himachal Pradesh',
    latitude: 31.1048,
    longitude: 77.1352,
    elevation_m: 2100.0,
    population: 31200,
    is_demo: true,
  },
  {
    id: 5,
    code: 'TN-NIL-05',
    name: 'Coonoor - Marappalam Incline',
    district: 'Nilgiris',
    state: 'Tamil Nadu',
    latitude: 11.3530,
    longitude: 76.7959,
    elevation_m: 1850.0,
    population: 17800,
    is_demo: true,
  },
  {
    id: 6,
    code: 'MH-RAI-06',
    name: 'Irshalwadi - Khalapur Escarpment',
    district: 'Raigad',
    state: 'Maharashtra',
    latitude: 18.9185,
    longitude: 73.2384,
    elevation_m: 480.0,
    population: 4500,
    is_demo: true,
  },
  {
    id: 7,
    code: 'KA-KOD-07',
    name: 'Madikeri - Bhagamandala Belt',
    district: 'Kodagu',
    state: 'Karnataka',
    latitude: 12.3887,
    longitude: 75.5298,
    elevation_m: 1060.0,
    population: 12400,
    is_demo: true,
  },
  {
    id: 8,
    code: 'UK-RUD-08',
    name: 'Kedarnath Valley - Gaurikund',
    district: 'Rudraprayag',
    state: 'Uttarakhand',
    latitude: 30.6521,
    longitude: 79.0345,
    elevation_m: 1980.0,
    population: 16800,
    is_demo: true,
  },
  {
    id: 9,
    code: 'HP-MAN-09',
    name: 'Pandoh Dam - Aut Tunnel Corridor',
    district: 'Mandi',
    state: 'Himachal Pradesh',
    latitude: 31.6720,
    longitude: 77.0540,
    elevation_m: 920.0,
    population: 19200,
    is_demo: true,
  },
  {
    id: 10,
    code: 'SK-EAS-10',
    name: 'Gangtok - Dikchu Valley Corridor',
    district: 'East Sikkim',
    state: 'Sikkim',
    latitude: 27.3912,
    longitude: 88.5284,
    elevation_m: 1650.0,
    population: 28400,
    is_demo: true,
  },
];

export const fallbackAssessments: RiskAssessment[] = [
  {
    id: 1,
    location_id: 1,
    location_name: 'Meppadi - Chooralmala Catchment',
    district: 'Wayanad',
    timestamp: new Date().toISOString(),
    hazard_score: 84.5,
    exposure_score: 76.0,
    overall_risk_score: 81.1,
    risk_category: 'CRITICAL',
    geotechnical_fs: 0.88,
    geotechnical_stability: 'UNSTABLE',
    model_confidence: 0.92,
    model_version_tag: 'rf-ensemble-v1.0.0',
    explanation: {
      top_factors: [
        {
          factor_name: 'rainfall_accum_24h',
          display_name: '24h Rainfall Accumulation',
          value: 142.5,
          unit: 'mm',
          contribution_score: 0.35,
          direction: 'INCREASES_RISK',
          description: 'Extreme cloudburst rainfall saturated colluvium layer',
        },
        {
          factor_name: 'geotechnical_fs',
          display_name: 'Factor of Safety (Fs)',
          value: 0.88,
          unit: 'Fs',
          contribution_score: 0.28,
          direction: 'INCREASES_RISK',
          description: 'Infinite slope limit equilibrium Fs below critical threshold 1.0',
        },
        {
          factor_name: 'slope_degrees',
          display_name: 'Slope Angle',
          value: 36.5,
          unit: 'deg',
          contribution_score: 0.20,
          direction: 'INCREASES_RISK',
          description: 'Steep hill slope exceeding angle of internal shearing resistance',
        },
      ],
      geotechnical_narrative: 'Limit equilibrium infinite slope stability analysis indicates driving shear stress exceeds resisting shear strength (Fs = 0.88). Subsurface saturation has elevated pore-water pressures.',
      ml_confidence_narrative: 'Random Forest tabular ensemble predicts high failure probability (92.4% confidence) driven by 72h antecedent rainfall and steep topography.',
      data_freshness_status: 'FRESH',
      missing_data_warnings: [],
    },
    is_demo: true,
  },
  {
    id: 2,
    location_id: 2,
    location_name: 'Pettimudi - Munnar Valley',
    district: 'Idukki',
    timestamp: new Date().toISOString(),
    hazard_score: 68.2,
    exposure_score: 62.0,
    overall_risk_score: 65.7,
    risk_category: 'HIGH',
    geotechnical_fs: 1.15,
    geotechnical_stability: 'QUASI_STABLE',
    model_confidence: 0.87,
    model_version_tag: 'rf-ensemble-v1.0.0',
    explanation: {
      top_factors: [
        {
          factor_name: 'rainfall_antecedent_72h',
          display_name: '72h Antecedent Rainfall',
          value: 195.0,
          unit: 'mm',
          contribution_score: 0.32,
          direction: 'INCREASES_RISK',
          description: 'High cumulative precipitation maintaining high groundwater table',
        },
        {
          factor_name: 'slope_degrees',
          display_name: 'Slope Angle',
          value: 32.0,
          unit: 'deg',
          contribution_score: 0.24,
          direction: 'INCREASES_RISK',
          description: 'Steep tea plantation escarpment with compromised root binding',
        },
      ],
      geotechnical_narrative: 'Fs is 1.15, classified as quasi-stable. Additional 25mm precipitation is modeled to reduce Fs below 1.0.',
      ml_confidence_narrative: 'Ensemble model indicates 78.5% probability of debris flow initiation.',
      data_freshness_status: 'FRESH',
      missing_data_warnings: [],
    },
    is_demo: true,
  },
  {
    id: 3,
    location_id: 3,
    location_name: 'Joshimath - Helang Slope',
    district: 'Chamoli',
    timestamp: new Date().toISOString(),
    hazard_score: 62.0,
    exposure_score: 88.0,
    overall_risk_score: 72.4,
    risk_category: 'CRITICAL',
    geotechnical_fs: 1.08,
    geotechnical_stability: 'QUASI_STABLE',
    model_confidence: 0.90,
    model_version_tag: 'rf-ensemble-v1.0.0',
    explanation: {
      top_factors: [
        {
          factor_name: 'exposure_score',
          display_name: 'Critical Lifeline Exposure',
          value: 88.0,
          unit: 'idx',
          contribution_score: 0.40,
          direction: 'INCREASES_RISK',
          description: 'High density urban infrastructure on moraine toe slope',
        },
      ],
      geotechnical_narrative: 'Moraine debris slope experiencing slow toe subsidence and structural distress.',
      ml_confidence_narrative: 'High consequence score elevates total risk to CRITICAL category.',
      data_freshness_status: 'FRESH',
      missing_data_warnings: [],
    },
    is_demo: true,
  },
  {
    id: 4,
    location_id: 4,
    location_name: 'Summer Hill - Totu Ridge',
    district: 'Shimla',
    timestamp: new Date().toISOString(),
    hazard_score: 48.0,
    exposure_score: 55.0,
    overall_risk_score: 50.8,
    risk_category: 'HIGH',
    geotechnical_fs: 1.28,
    geotechnical_stability: 'QUASI_STABLE',
    model_confidence: 0.84,
    model_version_tag: 'rf-ensemble-v1.0.0',
    explanation: {
      top_factors: [
        {
          factor_name: 'slope_degrees',
          display_name: 'Slope Angle',
          value: 29.5,
          unit: 'deg',
          contribution_score: 0.28,
          direction: 'INCREASES_RISK',
          description: 'Valley ridge slope with extensive road cutting',
        },
      ],
      geotechnical_narrative: 'Currently quasi-stable at Fs 1.28. Drainage blockages pose escalation risk.',
      ml_confidence_narrative: 'Moderate-high susceptibility under sustained monsoon conditions.',
      data_freshness_status: 'FRESH',
      missing_data_warnings: [],
    },
    is_demo: true,
  },
  {
    id: 5,
    location_id: 5,
    location_name: 'Coonoor - Marappalam Incline',
    district: 'Nilgiris',
    timestamp: new Date().toISOString(),
    hazard_score: 28.5,
    exposure_score: 35.0,
    overall_risk_score: 31.1,
    risk_category: 'MODERATE',
    geotechnical_fs: 1.54,
    geotechnical_stability: 'STABLE',
    model_confidence: 0.89,
    model_version_tag: 'rf-ensemble-v1.0.0',
    explanation: {
      top_factors: [
        {
          factor_name: 'geotechnical_fs',
          display_name: 'Factor of Safety',
          value: 1.54,
          unit: 'Fs',
          contribution_score: 0.35,
          direction: 'DECREASES_RISK',
          description: 'Adequate limit equilibrium resistance under current hydrological levels',
        },
      ],
      geotechnical_narrative: 'Slope is structurally stable (Fs 1.54) with moderate drainage capacity.',
      ml_confidence_narrative: 'Low likelihood of initiation unless rainfall exceeds 120mm/24h.',
      data_freshness_status: 'FRESH',
      missing_data_warnings: [],
    },
    is_demo: true,
  },
];

export const fallbackAlerts: AlertItem[] = [
  {
    id: 1,
    location_id: 1,
    location_name: 'Meppadi - Chooralmala Catchment',
    district: 'Wayanad',
    timestamp: new Date().toISOString(),
    risk_score: 81.1,
    severity: 'EVACUATION',
    trigger_condition: 'Factor of Safety dropped to 0.88 with 24h rainfall > 140mm',
    affected_infrastructure: [
      { name: 'Meppadi Primary Health Centre', type: 'HEALTHCARE', tier: 1 },
      { name: 'Chooralmala Bridge & Access Road', type: 'ROAD', tier: 2 },
    ],
    recommended_action: 'Trigger immediate Phase 1 evacuation along Chooralmala stream corridor. Pre-position NDRF Battalion 04.',
    status: 'ACTIVE',
    is_demo: true,
  },
  {
    id: 2,
    location_id: 3,
    location_name: 'Joshimath - Helang Slope',
    district: 'Chamoli',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    risk_score: 72.4,
    severity: 'WARNING',
    trigger_condition: 'Critical lifeline exposure score 88.0 on quasi-stable moraine slope',
    affected_infrastructure: [
      { name: 'Helang-Joshimath Highway NH-07', type: 'HIGHWAY', tier: 1 },
      { name: 'Municipal Water Intake Pipeline', type: 'WATER', tier: 2 },
    ],
    recommended_action: 'Halt heavy vehicular traffic along NH-07. Initiate structural displacement monitoring.',
    status: 'ACTIVE',
    is_demo: true,
  },
  {
    id: 3,
    location_id: 2,
    location_name: 'Pettimudi - Munnar Valley',
    district: 'Idukki',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    risk_score: 65.7,
    severity: 'WATCH',
    trigger_condition: 'Antecedent 72h rainfall reached 195mm (85% saturation)',
    affected_infrastructure: [
      { name: 'Tea Workers Residential Quarters', type: 'RESIDENTIAL', tier: 2 },
    ],
    recommended_action: 'Issue weather advisory to estate management. Keep emergency shelters prepared.',
    status: 'ACKNOWLEDGED',
    acknowledged_by: 'Idukki District Collector (Control Room)',
    acknowledged_at: new Date(Date.now() - 3600000).toISOString(),
    is_demo: true,
  },
];

export const fallbackInspections: InspectionTask[] = [
  {
    id: 1,
    location_id: 1,
    location_name: 'Meppadi - Chooralmala Catchment',
    district: 'Wayanad',
    infrastructure_name: 'Chooralmala Bridge Embankment',
    priority_score: 94.2,
    urgency_tier: 'P1_IMMEDIATE',
    assigned_team: 'Geotechnical Rapid Response Unit Alpha',
    status: 'DISPATCHED',
    rationale: 'Fs = 0.88, crown tension cracks reported near bridge abutment',
    field_notes: 'Team en route with piezometers and drone photogrammetry unit.',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    location_id: 3,
    location_name: 'Joshimath - Helang Slope',
    district: 'Chamoli',
    infrastructure_name: 'Helang-Joshimath Highway Section 14',
    priority_score: 86.5,
    urgency_tier: 'P1_IMMEDIATE',
    assigned_team: 'Border Roads Organisation Inspect Team',
    status: 'PENDING',
    rationale: 'Retaining wall distress and surface seepage detected along hairpin curve',
    field_notes: 'Awaiting clearance from local administration.',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 3,
    location_id: 2,
    location_name: 'Pettimudi - Munnar Valley',
    district: 'Idukki',
    infrastructure_name: 'Estate Drainage Culvert #3',
    priority_score: 74.0,
    urgency_tier: 'P2_HIGH',
    assigned_team: 'District Geological Survey Cell',
    status: 'PENDING',
    rationale: 'Culvert blockages causing surface water diversion onto debris fan',
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 4,
    location_id: 4,
    location_name: 'Summer Hill - Totu Ridge',
    district: 'Shimla',
    infrastructure_name: 'Shimla University Bypass Road',
    priority_score: 58.0,
    urgency_tier: 'P3_MEDIUM',
    status: 'PENDING',
    rationale: 'Road cut batter angle exceeds 60 degrees; monitoring weep holes',
    created_at: new Date(Date.now() - 28800000).toISOString(),
    updated_at: new Date(Date.now() - 28800000).toISOString(),
  },
];

export const fallbackInfrastructure: InfrastructureAsset[] = [
  {
    id: 1,
    name: 'Meppadi Primary Health Centre',
    asset_type: 'HEALTHCARE',
    latitude: 11.5380,
    longitude: 76.1310,
    location_id: 1,
    location_name: 'Meppadi - Chooralmala Catchment',
    district: 'Wayanad',
    lifeline_tier: 1,
    capacity: 250,
    exposure_weight: 0.95,
    is_demo: true,
  },
  {
    id: 2,
    name: 'Chooralmala Bridge & Access Corridor',
    asset_type: 'ROAD',
    latitude: 11.5350,
    longitude: 76.1340,
    location_id: 1,
    location_name: 'Meppadi - Chooralmala Catchment',
    district: 'Wayanad',
    lifeline_tier: 2,
    capacity: 1200,
    exposure_weight: 0.85,
    is_demo: true,
  },
  {
    id: 3,
    name: 'Helang-Joshimath Highway NH-07',
    asset_type: 'HIGHWAY',
    latitude: 30.5580,
    longitude: 79.5670,
    location_id: 3,
    location_name: 'Joshimath - Helang Slope',
    district: 'Chamoli',
    lifeline_tier: 1,
    capacity: 4500,
    exposure_weight: 0.98,
    is_demo: true,
  },
  {
    id: 4,
    name: 'Munnar Valley Tea Processing Plant',
    asset_type: 'COMMERCIAL',
    latitude: 10.1540,
    longitude: 77.0160,
    location_id: 2,
    location_name: 'Pettimudi - Munnar Valley',
    district: 'Idukki',
    lifeline_tier: 3,
    capacity: 350,
    exposure_weight: 0.60,
    is_demo: true,
  },
  {
    id: 5,
    name: 'Shimla Ridge Water Reservoir',
    asset_type: 'WATER',
    latitude: 31.1060,
    longitude: 77.1370,
    location_id: 4,
    location_name: 'Summer Hill - Totu Ridge',
    district: 'Shimla',
    lifeline_tier: 1,
    capacity: 15000,
    exposure_weight: 0.92,
    is_demo: true,
  },
];

export const fallbackHistoricalLandslides: HistoricalLandslide[] = [
  {
    id: 1,
    event_date: '2024-07-30',
    latitude: 11.5390,
    longitude: 76.1330,
    trigger_type: 'EXTREME_RAINFALL_CLOUDBURST',
    estimated_volume_m3: 450000,
    casualties: 350,
    damage_rating: 'CATASTROPHIC',
    notes: 'Major debris avalanche originating from Chooralmala shola crest following 300mm+ precipitation.',
    location_name: 'Meppadi - Chooralmala Catchment',
    is_demo: true,
  },
  {
    id: 2,
    event_date: '2020-08-07',
    latitude: 10.1550,
    longitude: 77.0150,
    trigger_type: 'EXTREME_RAINFALL',
    estimated_volume_m3: 180000,
    casualties: 66,
    damage_rating: 'SEVERE',
    notes: 'Pettimudi tea estate settlement buried under colluvial debris flow after 72h continuous deluge.',
    location_name: 'Pettimudi - Munnar Valley',
    is_demo: true,
  },
  {
    id: 3,
    event_date: '2023-01-05',
    latitude: 30.5570,
    longitude: 79.5660,
    trigger_type: 'SUBSIDENCE_SEEPAGE',
    estimated_volume_m3: 25000,
    casualties: 0,
    damage_rating: 'MODERATE',
    notes: 'Widespread structural cracking across 860 buildings leading to partial evacuation.',
    location_name: 'Joshimath - Helang Slope',
    is_demo: true,
  },
  {
    id: 4,
    event_date: '2023-08-14',
    latitude: 31.1055,
    longitude: 77.1360,
    trigger_type: 'FLASH_FLOOD_ROAD_CUT',
    estimated_volume_m3: 35000,
    casualties: 14,
    damage_rating: 'SEVERE',
    notes: 'Shiv Bawadi temple collapse at Summer Hill during torrential monsoon downpour.',
    location_name: 'Summer Hill - Totu Ridge',
    is_demo: true,
  },
];

export const fallbackOverview: DashboardOverview = {
  timestamp: new Date().toISOString(),
  data_mode: 'DEMO',
  active_model_version: 'rf-ensemble-v1.0.0 (calibrated)',
  total_monitored_zones: 5,
  critical_zones_count: 2,
  high_zones_count: 2,
  moderate_zones_count: 1,
  low_zones_count: 0,
  active_alerts_count: 2,
  pending_inspections_count: 3,
  max_24h_rainfall_mm: 142.5,
  data_health_overall: 'HEALTHY',
  highest_risk_locations: fallbackAssessments.slice(0, 3),
  critical_alerts: fallbackAlerts.filter(a => a.status === 'ACTIVE'),
  top_inspections: fallbackInspections.slice(0, 3),
};

export const fallbackSourcesHealth: DataSourceHealth[] = [
  {
    source_name: 'IMD Doppler Weather Radar & AWS Telemetry Mesh',
    provider_type: 'WEATHER_REST',
    freshness_seconds: 45,
    missing_value_rate: 0.0,
    coverage_pct: 100.0,
    quality_status: 'HEALTHY',
    is_demo: false,
    diagnostic_message: 'IMD Kochi & Thiruvananthapuram DWR feeds stream cloudburst reflectivity every 10 minutes.',
  },
  {
    source_name: 'ISRO NRSC Bhuvan Earth Observation & InSAR Gateway',
    provider_type: 'TERRAIN_ELEVATION',
    freshness_seconds: 120,
    missing_value_rate: 0.0,
    coverage_pct: 99.8,
    quality_status: 'HEALTHY',
    is_demo: false,
    diagnostic_message: 'Cartosat-3 and RISAT SAR coherence passes synchronized with sub-centimeter displacement.',
  },
  {
    source_name: 'Geological Survey of India (GSI) 1:10K NLSM Registry',
    provider_type: 'HISTORICAL_DATABASE',
    freshness_seconds: 300,
    missing_value_rate: 0.0,
    coverage_pct: 100.0,
    quality_status: 'HEALTHY',
    is_demo: true,
    diagnostic_message: 'National Landslide Susceptibility Mapping baseline calibrated across 10 vulnerable sectors.',
  },
  {
    source_name: 'NDMA Sachet Common Alerting Protocol (CAP-CP) Engine',
    provider_type: 'GEOTECHNICAL_DEMO',
    freshness_seconds: 15,
    missing_value_rate: 0.0,
    coverage_pct: 100.0,
    quality_status: 'HEALTHY',
    is_demo: true,
    diagnostic_message: 'Direct integration with DoT telecom cell-broadcast and state emergency operation centres.',
  },
  {
    source_name: 'Central Water Commission (CWC) Gauge Mesh',
    provider_type: 'WEATHER_REST',
    freshness_seconds: 60,
    missing_value_rate: 0.01,
    coverage_pct: 98.5,
    quality_status: 'HEALTHY',
    is_demo: true,
    diagnostic_message: 'Iruvanjippuzha & Teesta river basin discharge stages monitored within safe limits.',
  },
];

export const fallbackGeoJSON = {
  riskZones: {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        id: 1,
        geometry: {
          type: 'Polygon',
          coordinates: [
            [[76.115, 11.550], [76.148, 11.552], [76.155, 11.525], [76.128, 11.518], [76.115, 11.550]]
          ]
        },
        properties: {
          location_id: 1,
          name: 'Meppadi - Chooralmala Catchment',
          district: 'Wayanad',
          risk_category: 'CRITICAL',
          risk_score: 81.1,
          hazard_score: 84.5,
          exposure_score: 76.0,
          geotechnical_fs: 0.88,
          slope_degrees: 36.5,
          rainfall_accum_24h: 142.5,
          stroke_color: '#ef4444',
          fill_color: 'rgba(239, 68, 68, 0.60)',
        }
      },
      {
        type: 'Feature',
        id: 2,
        geometry: {
          type: 'Polygon',
          coordinates: [
            [[77.000, 10.165], [77.030, 10.160], [77.025, 10.140], [76.995, 10.145], [77.000, 10.165]]
          ]
        },
        properties: {
          location_id: 2,
          name: 'Pettimudi - Munnar Valley',
          district: 'Idukki',
          risk_category: 'HIGH',
          risk_score: 65.7,
          hazard_score: 68.2,
          exposure_score: 62.0,
          geotechnical_fs: 1.15,
          slope_degrees: 32.0,
          rainfall_accum_24h: 92.0,
          stroke_color: '#f97316',
          fill_color: 'rgba(249, 115, 22, 0.45)',
        }
      },
      {
        type: 'Feature',
        id: 3,
        geometry: {
          type: 'Polygon',
          coordinates: [
            [[79.550, 30.565], [79.580, 30.568], [79.578, 30.545], [79.548, 30.548], [79.550, 30.565]]
          ]
        },
        properties: {
          location_id: 3,
          name: 'Joshimath - Helang Slope',
          district: 'Chamoli',
          risk_category: 'CRITICAL',
          risk_score: 72.4,
          hazard_score: 62.0,
          exposure_score: 88.0,
          geotechnical_fs: 1.08,
          slope_degrees: 28.0,
          rainfall_accum_24h: 45.0,
          stroke_color: '#ef4444',
          fill_color: 'rgba(239, 68, 68, 0.60)',
        }
      },
      {
        type: 'Feature',
        id: 4,
        geometry: {
          type: 'Polygon',
          coordinates: [
            [[77.120, 31.115], [77.150, 31.118], [77.148, 31.095], [77.118, 31.098], [77.120, 31.115]]
          ]
        },
        properties: {
          location_id: 4,
          name: 'Summer Hill - Totu Ridge',
          district: 'Shimla',
          risk_category: 'HIGH',
          risk_score: 50.8,
          hazard_score: 48.0,
          exposure_score: 55.0,
          geotechnical_fs: 1.28,
          slope_degrees: 29.5,
          rainfall_accum_24h: 38.0,
          stroke_color: '#f97316',
          fill_color: 'rgba(249, 115, 22, 0.45)',
        }
      },
      {
        type: 'Feature',
        id: 5,
        geometry: {
          type: 'Polygon',
          coordinates: [
            [[76.780, 11.365], [76.810, 11.368], [76.808, 11.340], [76.778, 11.342], [76.780, 11.365]]
          ]
        },
        properties: {
          location_id: 5,
          name: 'Coonoor - Marappalam Incline',
          district: 'Nilgiris',
          risk_category: 'MODERATE',
          risk_score: 31.1,
          hazard_score: 28.5,
          exposure_score: 35.0,
          geotechnical_fs: 1.54,
          slope_degrees: 24.0,
          rainfall_accum_24h: 18.0,
          stroke_color: '#f59e0b',
          fill_color: 'rgba(245, 158, 11, 0.35)',
        }
      }
    ]
  },
  infrastructure: {
    type: 'FeatureCollection',
    features: fallbackInfrastructure.map(item => ({
      type: 'Feature',
      id: item.id,
      geometry: {
        type: 'Point',
        coordinates: [item.longitude, item.latitude]
      },
      properties: {
        id: item.id,
        name: item.name,
        asset_type: item.asset_type,
        location_id: item.location_id,
        location_name: item.location_name,
        district: item.district,
        lifeline_tier: item.lifeline_tier,
        capacity: item.capacity,
        exposure_weight: item.exposure_weight,
        is_demo: item.is_demo
      }
    }))
  },
  historicalLandslides: {
    type: 'FeatureCollection',
    features: fallbackHistoricalLandslides.map(item => ({
      type: 'Feature',
      id: item.id,
      geometry: {
        type: 'Point',
        coordinates: [item.longitude, item.latitude]
      },
      properties: {
        id: item.id,
        event_date: item.event_date,
        trigger_type: item.trigger_type,
        estimated_volume_m3: item.estimated_volume_m3,
        casualties: item.casualties,
        damage_rating: item.damage_rating,
        notes: item.notes,
        location_name: item.location_name,
        is_demo: item.is_demo
      }
    }))
  }
};

export const fallbackSitRep = {
  executive_summary: {
    generated_at: new Date().toISOString(),
    eoc_authority: 'National Disaster Response Force (NDRF) / State Disaster Management Authority (SDMA)',
    headline: 'CRITICAL MULTI-CATCHMENT LANDSLIDE HAZARD ELEVATION - IMMEDIATE EVACUATION RECOMMENDED FOR MEPPADI (WAYANAD)',
    operational_status: 'RED ALERT - ACTIVE DISASTER RESPONSE PHASE',
    total_catchments_monitored: 5,
    critical_hotspots_count: 2,
    active_alerts_count: 2,
    p1_immediate_inspections: 2,
  },
  critical_hotspots: [
    {
      location_name: 'Meppadi - Chooralmala Catchment',
      district: 'Wayanad',
      risk_score: 81.1,
      risk_category: 'CRITICAL',
      geotechnical_fs: 0.88,
      rainfall_24h_mm: 142.5,
      population_exposed: 14200,
      lifelines_at_risk: ['Meppadi Primary Health Centre', 'Chooralmala Bridge & Access Corridor'],
      primary_driver: 'Slope saturation exceeding internal friction threshold (Fs = 0.88)',
      recommended_action: 'Enforce mandatory 500m buffer evacuation along stream corridor. Pre-position amphibious rescue units.',
    },
    {
      location_name: 'Joshimath - Helang Slope',
      district: 'Chamoli',
      risk_score: 72.4,
      risk_category: 'CRITICAL',
      geotechnical_fs: 1.08,
      rainfall_24h_mm: 45.0,
      population_exposed: 23500,
      lifelines_at_risk: ['Helang-Joshimath Highway NH-07', 'Municipal Water Intake Pipeline'],
      primary_driver: 'Moraine toe instability coupled with critical lifeline infrastructure density',
      recommended_action: 'Reroute heavy traffic from NH-07. Initiate continuous automated total station monitoring.',
    },
  ]
};
